# -*- coding: utf-8 -*-
"""EMS_Case_study.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17PoggbPyjrEYoxb8W6PRsUdt1uIfh13g

#case study(Employee master list)

# Employee Management System


##Write a function which takes in 5 arguments id,first name,last name,salary,department and puts all details in list if ID already not exists
## 1 Add employee
## 2 remove employee by id
## 3 remove employee by name
## 4 Update Details
## 5 print details by ID
## 6 print details of all employees
## 7 exit
"""

## case study


# Write a function which takes in 5 arguments id,first name,last name,salary,department 
# and puts all details in list if ID already not exists
# 1 Add employee
# 2 remove employee by id
# 3 remove employee by name
# 4 Update Details
# 5 print details by ID
# 6 print details of all employees
# 7 exit


# remove employee by id
# find if the id exists in the list emp_id_list, if it exists find the index and remove from all lists
# if not exists tell user no such ID exists

# Remove Employee by name
# at first two inputs first name and last name
# if 1 record with first and last name found remove directly
# if no matching record show user wrong input
# match all the records with same name
# print out the ids of employees with same name
# ask for id which needs to be removed


# Update Details of Employee by ID
# find the id index in the list
# ask for 4 details except id that is firstname,lastname,salary,department
# update these details at thay specific index

# print details by ID
# find index of the id and print details of all parameters

id_all=[]
first_name_all=[]
last_name_all=[]
salary_all=[]
department_all=[]

## 1 ADD employee function

def case_employee(id,fname,lname,sal,dep):
  if id in id_all:
    print('ID already exists')
  else:
    id_all.append(id)
    first_name_all.append(fname)
    last_name_all.append(lname)
    salary_all.append(sal)
    department_all.append(dep)
    print('Employee with id: ',id,'added SUCCESSFULLY',)

## 2 REMOVE employee by ID

def remove_emp_id(id_to_remove):
  try:
    index_to_remove=id_all.index(id_to_remove)
    id_all.pop(index_to_remove)
    first_name_all.pop(index_to_remove)
    last_name_all.pop(index_to_remove)
    salary_all.pop(index_to_remove)
    department_all.pop(index_to_remove)
    print('Employee of id: ',id,'removed SUCCESSFULLY')
  except:
    print('ID does not exist...Please try valid id...')

# Remove Employee by name
# at first two inputs first name and last name
# if 1 record with first and last name found remove directly
# if no matching record show user wrong input
# match all the records with same name
# print out the ids of employees with same name
# ask for id which needs to be removed
## 3 Remove employee by Name:
def remove_emp_by_name(f_name,l_name):
  all_record=[]
  for k in range(len(first_name_all)):
    if first_name_all[k]==f_name:
      if last_name_all[k]==l_name:
        all_record.append(k)
  
  if len(all_record)==1:
    id_to_remove=id_all[all_record[0]]
    remove_emp_id(id_to_remove)
  
  elif len(all_record)>1:
    print('Multiple records of same name found')
    for c in all_record:
      print('ID:-',id_all[c])
    id_to_remove=int(input('Please enter employee Id to remove: '))
    remove_emp_id(id_to_remove)
  
  else:
    print('Wrong input received, try with correct first name and last name of employee')    


## 4 Update details by ID

def update_detail(id_to_update):
  try:
    index_to_update=id_all.index(id_to_update)
    update_field=-1
    while update_field!=5:
      print('Your options are: ')
      print('(1) Update first name')
      print('(2) Update last name')
      print('(3) Update employee salary')
      print('(4) Update employee department')
      print('(5) exit')
      update_field=int(input('enter your option here: '))

      if update_field==1:
        updated_fname=input('Enter updated first name here: ')
        first_name_all.pop(index_to_update)
        first_name_all.insert(index_to_update, updated_fname)
        print('Update SUCCESSFUL')
      
      elif update_field==2:
        updated_lname=input('Enter updated last name here: ')
        last_name_all.pop(index_to_update)
        last_name_all.insert(index_to_update, updated_lname)
        print('Update SUCCESSFUL')
      
      elif update_field==3:
        updated_salary=input('Enter updated salary here: ')
        salary_all.pop(index_to_update)
        salary_all.insert(index_to_update, updated_salary)
        print('Update SUCCESSFUL')
      
      elif update_field==4:
        updated_dep=input('Enter updated department here: ')
        department_all.pop(index_to_update)
        department_all.insert(index_to_update, updated_dep)
        print('Update SUCCESSFUL')
      
      elif update_field==5:
        print('Main Menu')
  except:
    print('Please enter valid employee ID')

## 5 print DETAILS by ID

def details_id(id_to_print):
  try:
    if id_to_print in id_all:
      index_to_display=id_all.index(id_to_print)
      print("========================================")
      print('Employee ID: ',id_all[index_to_display])
      print('Full name: ',first_name_all[index_to_display],last_name_all[index_to_display])
      print('Monthly salary: ',salary_all[index_to_display])
      print('Department :',department_all[index_to_display])
      print("========================================")
  except:
    print('Incorrect ID... Please enter valid ID')

option=-1
while option!=7:
  #print(id_all)
  #print(first_name_all)
  print('Your options are: ')
  print('(1) Add employee')
  print('(2) remove employee by id')
  print('(3) remove employee by name')
  print('(4) Update Details')
  print('(5) print details by ID')
  print('(6) print details of all employees')
  print('(7) exit')
  option=int(input("enter your option here: "))

  if option==1:
    id=int(input('input id: '))
    fname=input('first name: ')
    lname=input('last name: ')
    sal=input('salary: ')
    dep=input('department: ')
    case_employee(id,fname,lname,sal,dep)
  
  elif option==2:
    id_to_remove=int(input('enter id to be removed: '))
    remove_emp_id(id_to_remove)
  
  elif option==3:
    f_name=str(input('fist name of employee: '))
    l_name=str(input('last name of employee: '))
    remove_emp_by_name(f_name,l_name)
  
  elif option==4:
    id_to_update=int(input('Enter the employee ID to update'))
    update_detail(id_to_update)
  
  elif option==5:
    id_to_print=int(input('enter id for details: '))
    details_id(id_to_print)

  elif option==6:
    for i in id_all:
      details_id(i)

  elif option==7:
    print('Gracias, adios!!!')

d=['man','jon','jovi']
d.pop(0)
d.insert(0,'manoj')
print(d)

lst=['a','b','c']
def find(x):
  try:
    if x in lst:
      print(x)
  except:
    print('no record found')
x=input('enter an alphabet: ')
find(x)
