# -*- coding: utf-8 -*-
"""DataType.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15FplIZdzuowqup5PJp2z2ifTEjOp8Qtw
"""

print("Welcome to BDS29 at Takeo")

"Welcome to BDS29 at Takeo"

"""#**Data Type**

Standard Data Type

  1. Number
        a. Interger
        b. Float
        c. Complex
  2. Boolean
  3. String
"""

#**Integer**

int1 = 12
print(int1)
print(type(int1))

#**Integer**

int1 = -12
print(int1)
print(type(int1))

#**Float**

flt1 = 3.1414
print(flt1)
print(type(flt1))

#**Float**

flt1 = -3.1414
print(flt1)
print(type(flt1))

#**Complex**

cmplx1 = 2+3j
print(cmplx1)
print(type(cmplx1))

#**Complex**

bavindra = -2-3j
print(bavindra)
print(type(bavindra))

#**Boolean**

bavindra = True
print(bavindra)
print(type(bavindra))

#**Boolean**

bavindra = False
print(bavindra)
print(type(bavindra))

#**String**

str1 = 'Python Programming'
print(str1)
print(type(str1))



#**String**

str1 = "Python Programming"
print(str1)
print(type(str1))

#**String**

str1 = '''Python Programming'''
print(str1)
print(type(str1))

#**String**

str1 = """Python Programming"""
print(str1)
print(type(str1))

str2 = my name is "manoj". I love 'python language'

str3 = "my name is "manoj". I love 'python language'"

str2 = '''my name is "manoj". I love 'python language'.'''
print(str2)
print(type(str2))

str2 = 'python programming'
print(str2[7:10])

str1 = "amar akbar anthony"
print(str1[0])
print(str1[1])
print(str1[2])
print(str1[3])
print(str1[5])
print(str1[6])
print(str1[7])
print(str1[8])
print(str1[9])
print(str1[11])
print(str1[12])
print(str1[13])
print(str1[14])
print(str1[15])
print(str1[16])
print(str1[17])

str1 = 'albert pinto ko gussa aaya'
print(str1[0:13])
print(str1[7:16])
print(str1[13:22])
print(str1[16:26])
print(str1[0:len('albert pinto')], len('albert pinto'))
str1[0:len('albert pinto')], len('albert pinto')

str1 = 'python programming'
print(str1[:])
print(str1[::])
print(str1[::1])#skip or jump with ::
print(str1[::2])#skip one value with ::2
print(str1[::3])
print(str1[::-1])# reverse the string
print(str1[-1:-10:-1])#third index is necessary -1

"""can we jump in reverse??"""

str1="hello python programming"
print(str1[0:-3])#start:end:step, -3 indicates counting from the end
print(str1[0:-3:2])
print(str1[-1:-10:-1])

dir(str)
print(str1.capitalize())#capitalize first letter
print(str1.casefold())#lowercae all characters
print(str1.center(30))#centers the sting with space in the ends
print(str1.center(28, "v"))

a="hello"
b="world"
c=a+b #'+' acts as a concactinator
c

"""triple quotes ''' or ''' used for the strings in multiple lines
you can insert ' in the string as long as you are using " or triple quotes
"""

#count
count_string="hello world, i hope the world is a better place to live for everyone"
count_string.count("world")

print(str1.endswith("ing"))
print(str1.endswith("ng"))
print(str1.find("pro"))
print(str1[13:16])

#string is immutable(can't be formatted once its set)
#only way to format is
test_string="hello, i am {0}, i live in {1}, {2}"

print(test_string.format("Manoj","Blacksburg","Virginia"))
test_string="hello, i am {name}, i live in {city}, {state}"
print(test_string.format(name="Manoj",city="Blacksburg",state="Virginia"))

