# -*- coding: utf-8 -*-
"""List_Tuples.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Oc1AdEQVIlRNy4GcBm9konLNcwraNraY
"""

#pop function=removes the list element from the end(left)
#pop(3)=removes 4th element from i.e. 3rd index element
lst1=['apple', 'banana', 'cherries', 'date', 'eggfruit', 'fig', 'grapes', 'honey fruit']
print(lst1)
lst1.pop()
print(lst1)
lst1.pop()
print(lst1)
lst1.pop()
print(lst1)
lst1.pop(2)
print(lst1)

#remove function
#delete the particular value, different than above where pop function only removes one specific index element, however the remove function/n
##deletes multiple items whatever is in the function
lst1=['apple', 'banana', 'cherries', 'date', 'eggfruit', 'fig', 'grapes', 'honey fruit']
print(lst1)
lst1.remove('fig')
print(lst1)
lst1=['apple', 'banana', 'cherries', 'date', 'apple', 'eggfruit', 'fig', 'grapes', 'honey fruit']
lst1.remove('apple')#removes both the element 'apple' from the list
print(lst1)

lst1=[-3-4j,6.7,'a',1,'b',2,3.14,'c',3,1+2j,True,False,'Python','PYthon','PYTHON','python']
print(lst1)
print(lst1.index('Python'))
lst1.reverse()
print(lst1)
lst1.reverse()
print(lst1)
lst1.pop()
print(lst1)
lst1.pop()
print(lst1)
lst1.remove('Python')
print(lst1)
lst2=['z',4.5,True]
print(lst2)
lst1.append(lst2)
print(lst1)
lst1.extend(lst2)
print(lst1)
lst1.insert(0,'programming')
print(lst1)
print(lst1.count(True))
print(lst1)
lst1.clear()
print(lst1)
lst1.copy()

#tuple are data type same as list but enclosed by '()' small bracket
#tuple is IMMUTABLE (tuple data type is used when you have to freeze the data)
tup1=(1,2,3,4,5,6,7,8,9,0)
print(tup1.count(1))
print(tup1.index(3))
tup1=('apple','banana','cherries','date','eggfruit','fig','grapes','honey fruit','mango','pomegranate')
#+ve indexing and +ve slicing
print(tup1[::])
#-ve indexing and -ve slicing
print(tup1[::-1])
print(tup1[-1:-(len(tup1)+1):-1])
#+ve indexing and -ve slicing
print(tup1[9::-1])
#-ve indexing and +ve slicing
print(tup1[-10::])

#set
set1={0,1,1,2,2,3,3,3,4,4,4,4,5,5,5,5,5,6,6,6,6,6,6,7,7,7,7,7,7,7,8,8,8,8,8,8,8,8,9,9,9,9,9,9,9,9,9}
print(set1)
print(type(set1))

set1={0,1,1,True,False,None,'Python','python','PYTHON',2,2,3,3,3}
print(set1)
print(type(set1))

#in above example, no True and False because the numeric value of True is 0 and false is 1, which already exist in the set

#copy function
lst1=[1,2,3,4,5,6,11,4,88]
lst1_copy=lst1.copy()
print(lst1)
print(lst1_copy)
lst1_copy[0]=0
print(lst1_copy)

tpl1=1, #anything comma separated is a tuple, don't need to be enclosed by ()
print(type(tpl1))
tpl1=1,2,3,4
print(type(tpl1))

#can convert list into tuple
lst1=[1,2,'a','b']
tup1=tuple(lst1)
print(lst1)
print(tup1)
print(type(tup1))

str1="hello my friend how are you doing today"
print(str1)
str1.replace(" ","")
print(str1)
set1=set(str1)
print(set1)

lst1=[1,10,18,19,66,101,85]
lst1.sort()
lst1[-1]

list_str=['Harry',"potter","and","the","goblet","of","fire"]
str1=str(list_str)
print(str1.replace("', '", " "))
' '.join(list_str)
print(type(' '.join(list_str)))

tup1=("hey","how","are","su")
lst1=list(tup1)
lst1[3]="you"
' '.join(lst1)

