# -*- coding: utf-8 -*-
"""String_practice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s_5i9EkoO23lN8VulNxCdtBHzzL9LlKj
"""

test_string= "Hello Python Programming"

# STRING ARE IMMUTABLE
test_string[0]="h"

# INDEXS 0,2,4
# left to right side
# right to left side negative indexing

test_string[0:-3]

test_string="hello python programming"

test_string.capitalize()

dir(test_string)

a="hello"
b="world   "
c=a+b

print("abcxzasdasdas'daa'sdasd'sadsa'dasdsd'sadsa'dasdsadasdasd")

# Lowers all the characters
test_string="hello PYTHON programming"
test_string.casefold()

test_string.center(28,"$")

count_string="hello world , i hope the world is a better place to live for everyone"
count_string.count("world")

test_string="hello PYTHON programming"
test_string.endswith("ing")

test_string="               hello PYTHON programming  "
test_string.expandtabs()

#finds the lowest substring inside a string. If string does not exists it returns -1
test_string="hello PYTHON programming pro"
print(test_string.find("pro"))
print(test_string[13:16])

test_string="Hello my name is {fname} , i am {age}"
test_string.format(fname="Rohit",age="Programmer")

test_string="hello PYTHON programming pro"
test_string.islower()

test_string="PYTHON"
test_string.isupper()

test_string="hello PYTHONß"
print(test_string.lower())
print(test_string.casefold())

#1st argument is what you want to replace, 2nd argument with what you want to replace
test_string
test_string.replace("PYTHON111", "python")

#split function
a="""hello
PYTHON
programming
pro"""
print(a.split(' '))
print(a.split('\n')) #\n is the new line connector that is hidden
b="hello python programming pro"
print(b.split('p'))

#clean all the spaces, tabs spaces(\t), and new lines(\n) from the string on the RIGHT OR LEFT, wont work if its in between
test_string = "     \n \t    hey high how are you          \t"
print(test_string.strip())
test_string = "   hey   \n \t    how high are you       \n \n \n"
print(test_string.strip())
test_string.strip()

#join only works for list of strings
list_temp=['hello', 'PYTHON', 'programming', 'pro']
print(' '.join(list_temp))
print('$'.join(list_temp))
list_temp=["1", "2", "3", "4", "22"]
print(''.join(list_temp))

#...cntd
list_temp=[1,2,3,4,22]
''.join(list_temp)

##list
#are mutable
list_demo=[1,2,3,4,5,6]
list_demo[1]=88
print(list_demo)

#list functions
#append function helps us to add the elements to the existing list(@ the last index of the list)
list_demo.append("Hello")
list_demo

#sort function
#should make sure all the elements are either all integer or all string(including numbers)
list_demo=[1,5,88,22,4,53,-1]
list_demo.sort()
print(list_demo)
list_demo=['a', 'b', 't', 'w', '1', '22']
list_demo.sort()
print(list_demo)

#append vs extend function
list_demo_1=['b','c','a','n']
list_demo_2=['hello', 'python']
list_demo_1.append(list_demo_2)
print(list_demo_1)

#extend
list_demo_1=['b','c','a','n']
list_demo_2=['hello', 'python']
list_demo_1.extend(list_demo_2)
print(list_demo_1)

